version: '3'
services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: php-minimal
      MYSQL_USER: devuser
      MYSQL_PASSWORD: devpass
    ports:
      - "9906:3306"
    volumes:
      - web-db:/var/lib/mysql
  web:
    build:
      dockerfile: docker/Dockerfile
      context: ./
    environment:
      SHELL: /bin/bash
    volumes:
      - ./src:/work/src
    depends_on:
      - db
    ports:
      - "8100:80"
    links:
      - db
volumes:
  web-db:
